README.md
src/derivers/bip32.js
src/derivers/bip39.js
src/derivers/index.js
src/index.d.ts
src/index.js
test/index.js

This PR adds input validation to ensure that only properly formatted paths are processed by `deriveKeyFromPath`. Aside from internal import/export refactoring, the only functional change is the added input validation, and the tests, which are functionally unchanged, pass.
This PR is intended as the first entry before a major version bump, due to this package's anticipated production use. Therefore, the following breaking, but not cryptographically relevant changes, are made:
- `deriveKeyFromPath`: Change the order of parameters
- The first parameter was often `null`, which is unergonomic
- Add `index.js` file to `derivers` directory, re-export individual derivers from there
- We (I?) love being agnostic of directory structure when importing!
- Update readme
- Delete dead code

Add input validation, minor refactor

---

src/index.js
test/index.js

This updates the multipath validation to allow for a broader range of sub-paths, and adds unit tests for the input validation. Paths starting with `bip32` segments will still require a `parentKey` to be specified, and paths starting with `bip39` will still require that **no** `parentKey` is specified. Paths longer than 5 `bip32` segments will not be accepted, because [BIP-44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) only defines paths of length 5, excluding the seed.
Specifically, we change the quantifier for intermediate `bip32` path segments of the multipath RegEx from `{3,4}` to `{0,4}`. In conjunction with the other RegEx validators, this means that the following multipaths will now be accepted:
```
bip32:44'/bip32:60'/bip32:0'/bip32:0/bip32:0 …
```

Fix multipath RegEx

---

.circleci/config.yml
.eslintrc.js
.gitignore
package.json
src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/index.js
src/derivers/index.ts
src/index.d.ts
src/index.ts
src/types/bip39.d.ts
test/index.js
tsconfig.json
yarn.lock

Migrates this package to TypeScript. Adds:
- New package scripts
- TypeScript dependencies
- tsconfig.json
- TypeScript source
- Moves some functions around within files
- No functional changes _except_ some internal import / export behavior
- eslint config
- CI config
Closes #9

Migrate to TypeScript

---

src/derivers/bip39.ts
src/index.ts
test/index.js

Fixes a bug in input validation where BIP-39 seed phrases could contain non-lowercase letters.

Ensure bip39 validation rejects non-lowercase seed phrases

---

src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/index.ts
src/index.ts
test/index.js

Ensures that `deriveKeyFromPath` `parentKey` parameter is optional. This required some refactoring of the internal derivers, since BIP-32 derivation requires a `parentKey` while BIP-39 does not. The public interface of this package remains unchanged.

Fix deriveKeyFromPath interface, refactor derivers

---

.eslintrc.js
README.md
jest.config.js
package.json
src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/HDTreeNode.ts
src/constants.ts
src/derivation.test.ts
src/derivation.ts
src/derivers/bip32.ts
src/derivers/bip39.ts
src/index.test.ts
src/index.ts
src/indext.test.ts
src/utils.ts
test/__snapshots__/reference-implementations.test.ts.snap
test/fixtures.ts
test/reference-implementations.test.ts
test/types/eth-hd-keyring/index.d.ts
tsconfig.test.json
yarn.lock

This PR attempts to refashion this package from an experimental key derivation module into something that we and our users can trust in production. This is accomplished by (1) adding numerous reference implementation tests (see `test/reference-implementations.test.ts`) and (2) adding new abstractions over our low-level key derivation functions. 
(2) is accomplished by the addition of two new classes, `BIP44Node` and `BIP44CoinTypeNode`, and associated utility functions. The API isn't perfect, but it's extremely easy to use on the address key derivation end, i.e. by our users. See the updated README and unit tests for details. Unit test coverage is at 100%.
This PR will be followed up by an ESLint update to add JSDoc linting, as well as release automation actions and completing repository …

@metamask/key-tree 3.0

---

.eslintrc.js
src/BIP44CoinTypeNode.ts
src/BIP44Node.ts
src/derivers/bip32.ts
src/derivers/index.ts
src/utils.ts

We hate interfaces, and they must be driven from this Earth in favor of object types.

Forbid TypeScript interfaces

---

package.json
test/fixtures.ts
test/reference-implementations.test.ts
yarn.lock

This removes the (dev) dependency on `keccak` and `secp256k1`, and also speeds up the tests a bit. All fixtures are extracted from the implementations.

Use hardcoded fixtures instead of calling implementations

---

README.md
src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/constants.ts
src/derivers/bip32.ts
src/utils.ts

This makes it possible to use a hardened `change` and `address_index`.
- Changed types to allow both hardened and unhardened indices for these paths.
- Changed some validation functions to allow both hardened and unhardened indices for these paths.
- Added an option `isHardened` to the deriver function, to derive a hardened `address_index`.
Closes #34.

Allow deriving hardened `change` and `address_index`

---

src/BIP44CoinTypeNode.ts

It's possible to get all symbols in an object using `Object.getOwnPropertySymbols`, so it's still possible to access the node here. This replaces the symbol with a `#private` field, making it inaccessible.

Replace node symbol with private field

---

jest.config.js
package.json
tsconfig.build.json
tsconfig.json
tsconfig.test.json

Based on MetaMask/controllers#732. Closes #47.
I also removed `tsconfig.test.json` since it doesn't seem to make any difference for running tests.

Extract build-only TypeScript configuration

---

src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/derivers/bip32.ts
test/fixtures.ts
test/reference-implementations.test.ts

~~Needs to be rebased after #43 is merged.~~ Done.
This PR adds convenience methods to get the (Ethereum) address and public key from an HD node.
**Why use a function instead of a getter?**
The method for deriving a public key from a private key can be async (in the case of `ed25519` for example), so it had to be an async function.
Closes #45.

Add convenience methods for public keys and addresses

---

src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/curves/curve.ts
src/curves/ed25519.test.ts
src/curves/ed25519.ts
src/curves/secp256k1.ts
src/derivation.test.ts
src/derivation.ts
src/derivers/bip32.test.ts
src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/index.ts
test/fixtures.ts
test/reference-implementations.test.ts

Closes #46.
Additional to adding support for public key derivation, I changed the signatures for some functions to use objects, rather than tuples or parameters. This prevents situations where we need to pass `undefined` in place for a private key, for example.

Add support for public key derivation

---

package.json
src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/curves/curve.ts
src/curves/ed25519.test.ts
src/curves/ed25519.ts
src/curves/secp256k1.ts
src/derivation.test.ts
src/derivation.ts
src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/index.ts
src/extended-keys.test.ts
src/extended-keys.ts
src/utils.test.ts
src/utils.ts
test/reference-implementations.test.ts
yarn.lock

Closes #44.
This PR adds a getter to the `BIP44Node` class to get an extended public or private key, and expands the `fromExtendedKey` function to make it possible to create a node from a stringified extended public or private key.
To make this possible, two new fields are introduced in `SLIP10Node`, `index` and `parentFingerprint`. These are part of the extended keys, so need to be kept track of. Additionally, to reduce complexity in the derivation code, all derivation functions now return a `SLIP10Node` instance, rather than an object containing the new key, chain code, etc.
Note that extended keys are not available for `SLIP10Node`s, since they are not defined in SLIP-10. Its only possible to use extended keys with BIP-44 nodes using `secp256k1`.

Add extended public (`xpub`) and private (`xprv`) keys

---

src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts

Before this change, we only exposed the compressed public key as `Buffer`. For convenience, this adds a new field which returns the compressed public key as hexadecimal string, similar to the `publicKey` (uncompressed public key as hexadecimal) field.

Add convenience field for getting the compressed public key

---

.yarn/plugins/plugin-git-hooks.js
.yarnrc.yml
package.json
yarn.lock

Closes #73.
This replaces the `postinstall` script with a Yarn plugin which calls `simple-git-hooks` after running `yarn`.

Replace postinstall script with Yarn plugin

---

src/SLIP10Node.test.ts
src/utils.test.ts
src/utils.ts

From the BIP-32 specification:
> Extended keys can be identified by the Hash160 (RIPEMD160 after SHA256) of the serialized ECDSA public key K, ignoring the chain code.
We were only taking the `RIPEMD160` hash, rather than `RIPEMD160` after `SHA256`.

Fix fingerprint derivation

---

src/index.ts

This fixes a type issue in packages using `key-tree`. Otherwise it would result in this:
```
../../node_modules/@metamask/key-tree/dist/index.d.ts:11:37 - error TS2552: Cannot find name 'BufferConstructor'. Did you mean 'NumberConstructor'?
11 export declare const PackageBuffer: BufferConstructor;
~~~~~~~~~~~~~~~~~
```
A possibly better solution is to remove this export entirely, as I don't think we're using it anywhere? @rekmarks

Export Buffer from `buffer` package explicitly

---

.eslintrc.js
package.json
src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/curves/curve.ts
src/curves/ed25519.test.ts
src/curves/ed25519.ts
src/curves/secp256k1.test.ts
src/curves/secp256k1.ts
src/derivation.test.ts
src/derivers/bip32.test.ts
src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/index.ts
src/extended-keys.test.ts
src/extended-keys.ts
src/index.test.ts
src/index.ts
src/utils.test.ts
src/utils.ts
test/fixtures.ts
yarn.lock

`Buffer` is a Node.js API and does not work in browsers without polyfills. This swaps out all usage of `Buffer` with `Uint8Array`, to make this library fully browser compatible without the need for polyfills.

Swap out Buffer with browser-compatible Uint8Array

---

README.md
src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/constants.ts
src/curves/ed25519.test.ts
src/derivation.test.ts
src/derivers/bip32.test.ts
src/derivers/bip32.ts
src/extended-keys.test.ts
src/extended-keys.ts
src/utils.test.ts
src/utils.ts
test/reference-implementations.test.ts

To make it clear that we no longer use Node.js `Buffer`s, I renamed all usage of `Buffer` to `Bytes` or `Uint8Array` (depending on context).

BREAKING: Rename all occurrences of `Buffer` with `Bytes` or `Uint8Array`

---

package.json
src/derivers/bip39.ts
yarn.lock

We are updating all instances of `bip39` across our packages to use the `@metamask/scure-bip39` (our fork of `@scure/bip39`) - which allows us to pass around SRP's as `Uint8Array`s rather than plain strings for security purposes.
Currently this change may also be blocking: https://github.com/MetaMask/metamask-extension/pull/17056

Update `bip39` implementation to `@metamask/scure-bip39`

---

src/BIP44CoinTypeNode.test.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/constants.ts
src/derivation.test.ts
src/derivation.ts
src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/index.ts
src/utils.test.ts
src/utils.ts

This adds support for passing mnemonic phrases as `Uint8Array`, in all places where we accept them. The expected format is the same as the format we use in `@metamask/scure-bip39`.
The derivation path can now look like `[new Uint8Array(), 'bip32:...', ...]`. Only the first BIP-39 segment can be a `Uint8Array`, it's not supported for BIP-32 segments.
Closes #106.

Accept BIP-39 mnemonic phrase as Uint8Array

---

src/SLIP10Node.test.ts
src/derivation.ts

This fixes a regression introduced in #107. The bytes-based derivation wasn't tested for `ed25519`, and was broken due to a missing curve parameter.

Add missing curve parameter

---

src/curves/secp256k1.test.ts
src/curves/secp256k1.ts

If the tweak equals zero, the generated child public key is the same as the parent public key. We have to validate that it has at least one non-zero byte.
Related to MM-02-001.

Validate tweak passed to `publicAdd`

---

src/derivers/bip32.test.ts
src/derivers/bip32.ts

If the tweak equals zero, the generated child private key is the same as the parent private key. We have to validate that it has at least one non-zero byte.
Related to MM-02-002.

Validate tweak passed to `privateAdd`

---

src/BIP44CoinTypeNode.test.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/utils.test.ts
src/utils.ts

`0x000...000` is a valid private key for `ed25519` (since all private keys are valid). Previously we would always reject this private key, due to the function used to validate bytes. I've updated it to use the curve function to check if a private key is valid.
Related to MM-02-007.

Allow zero private key for `ed25519`

---

src/BIP44Node.test.ts
src/SLIP10Node.test.ts
src/derivation.test.ts
src/derivers/bip39.test.ts
src/derivers/bip39.ts
src/derivers/index.ts
test/reference-implementations.test.ts

This validates that:
- The master private key is greater than zero and less than the order of the curve.
- The seed is within 16 and 64 bytes, as per the BIP-32 specification.
Related to MM-02-003 and MM-02-004.

Validate that master private key and seed are within bounds

---

src/BIP44CoinTypeNode.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/constants.ts
src/derivation.test.ts
src/derivation.ts
src/derivers/bip32.test.ts
src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/index.ts
src/derivers/shared.test.ts
src/derivers/shared.ts
src/derivers/slip10.test.ts
src/derivers/slip10.ts
src/utils.test.ts
src/utils.ts
test/fixtures.ts
test/reference-implementations.test.ts

This replaces the specification field added in #120, with a new path type `slip10:`. This means that you can now use something like `["slip10:44'", "slip10:60'", /* ... */]` as derivation path, as well as the current `bip32:` derivation paths. This simplifies the BIP-32 derivation logic, and separates SLIP-10 and BIP-32 specific logic to a separate file.
While BIP-32 and SLIP-10 are mostly the same, there are some subtle differences. Projects that require full compatibility with one or the other spec can now choose based on the path type.
This works:
```ts
const node = SLIP10Node.fromExtendedKey({
/* ... */,
curve: 'secp256k1',
});
node.derive([`slip10:0'`, `slip10:1`]);
```
This also works:
```ts
const node = SLIP10Node.fromExtendedKey({
/* ... */,
curve: 'secp256k1',
}); …
```

BREAKING: Remove specification field in favour of SLIP-10 path type

---

README.md

This adds some docs regarding the new `slip10:` path type, and updates some existing docs.

Update docs to include latest changes

---

package.json
yarn.lock

This bumps `@metamask/utils` to the latest version, `6.0.1`.

Bump `@metamask/utils` to `6.0.1`

---

src/constants.ts
src/index.test.ts
src/index.ts
src/utils.test.ts
src/utils.ts

This PR adds a new function, `isValidBIP32Path`, which can be used to check if a string is a valid BIP-32 path in the form `${number}'`. It will check if the index is `0 <= n <= 2**32 - 1`.

Add `isValidBIP32PathSegment` function

---

src/constants.ts
src/utils.test.ts
src/utils.ts

Rather than checking if the segment is within `2^32-1` (max value for hardened indices), we need to check if the index is within `2^31-1` (max value for unhardened indices).

Check if BIP-32 path segment is `<= 2^31-1`

---

package.json
yarn.lock

In #139 I accidentally added the `postinstall` script again, since we're using that in the Snaps repo too. That doesn't work for this however, because `key-tree` is a public package, and using it causes installation to fail. Removing them makes it easier to standardise the repo and avoid these issues.
Closes #145.

Remove git hooks

---

src/derivers/index.test.ts
src/derivers/index.ts
src/index.test.ts
src/index.ts

These functions are used in the Snaps repo, but cannot be imported anymore from `./dist` after #147.

Export `mnemonicPhraseToBytes` and `createBip39KeyFromSeed`

---

scripts/generate-vectors.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/constants.ts
src/curves/curve.ts
src/curves/ed25519.ts
src/curves/ed25519Bip32.test.ts
src/curves/ed25519Bip32.ts
src/curves/index.ts
src/curves/secp256k1.ts
src/derivation.test.ts
src/derivation.ts
src/derivers/bip39.test.ts
src/derivers/bip39.ts
src/derivers/cip3.test.ts
src/derivers/cip3.ts
src/derivers/cip3Icarus.test.ts
src/derivers/cip3Icarus.ts
src/derivers/index.ts
src/derivers/shared.ts
src/index.test.ts
src/index.ts
src/utils.test.ts
src/utils.ts
test/fixtures.ts
test/vectors.test.ts

- currently, this lib supports `secp256k1` and `ed25519`
- while developing a Snap for Cardano, we realized that keys derived by snap, using (`getBip32Entropy`) are different from keys that would standard Cardano wallet give, for the same mnemonic
- this inconsistency could lead to confusion and interoperability issues
- currently developed Cardano snap, relies on these changes, and is blocked by this. (note that changes need to be made also to `metamask-snaps` and `metamask-extension` repos, which are ready, awaiting feedback on this)
- by supporting derivation which is consistent with Cardano standard, we enable current Cardano users to use their existing mnemonics in Metamask and get the same wallet they used until now.
- similarily, we would enable current Metamask users to use their …

Support Cardano key derivation according to CIP3-Icarus

---

src/derivers/cip3.ts

As brought up in the recent audit of `key-tree`, modular reduction here is redundant, and does not change the result of the function.
Related to MM-04-002 WP.

Remove unneeded modular reduction in CIP-3 private key derivation

---

src/derivers/bip39.test.ts
src/derivers/bip39.ts

This validates that the entropy size to create the CIP-3 master node is between 16 and 64 bytes long.

Validate CIP-3 master node entropy size

---

src/index.test.ts
src/index.ts

This adds an export for the `getBIP44CoinTypeToAddressPathTuple` function, making it importable from `@metamask/key-tree`.
Closes #168.

Export `getBIP44CoinTypeToAddressPathTuple` function

---

.yarn/patches/@ts-bridge-cli-npm-0.1.4-7b3932d7f6.patch
package.json
yarn.lock

Patch `ts-bridge` to stop transforming named imports, fixing an ESM issue with the current build, unblocking PRs on the MetaMask extension side.
Conversation around upstreaming this is still pending: https://github.com/ts-bridge/ts-bridge/pull/18

Fix ESM imports

---

package.json
yarn.lock

- See https://github.com/MetaMask/snaps/pull/2445
- See https://github.com/MetaMask/core/pull/3645

Bump `@metamask/utils` from `^8.3.0` to `^9.0.0`

---

src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/extended-keys.ts

This adds an `extendedKey` property to SLIP-10 nodes, which returns the BIP-32 serialised extended key. This only works for `secp256k1` nodes, as other standards don't specify a standard for serialisation, and the length of the keys is different across curves.
I've also updated `SLIP10Node.fromExtendedKey` to accept a serialised extended key, instead of an options object.

Add extended key property to `SLIP10Node`

---

src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/cryptography.test.ts
src/cryptography.ts
src/derivation.ts
src/derivers/bip32.ts
src/derivers/bip39.test.ts
src/derivers/bip39.ts
src/derivers/cip3.ts
src/derivers/index.test.ts
src/derivers/index.ts
src/derivers/shared.ts
src/derivers/slip10.ts
src/index.test.ts
src/index.ts
src/utils.ts
test/reference-implementations.test.ts
test/vectors.test.ts
tsconfig.json

This adds cryptographic functions like `hmacSha512`, `pbkdf2Sha512`, with the option to use a custom implementation of these functions. This can be beneficial in environments like React Native, where the native implementation may be much faster than the JavaScript fallback.
These functions will now also use the Web Crypto API if available, which in itself results in a good performance improvement compared to the JavaScript functions.
Closes #195.

Add cryptographic functions with option to specify custom functions

---

.depcheckrc.json
jest.config.js
src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/constants.ts
src/derivation.ts
src/derivers/bip32.test.ts
src/derivers/bip39.ts
src/derivers/index.ts
src/derivers/shared.ts
src/derivers/slip10.test.ts
src/extended-keys.test.ts
src/extended-keys.ts
src/utils.test.ts
src/utils.ts
test/fixtures.ts

BIP-32 specifies four different "versions" for extended keys. Public and private, but also mainnet and testnet. Previously we just assumed mainnet, because that's what's used for Ethereum, but to support other networks (such as Bitcoin), I've added a network field (i.e., `mainnet` or `testnet`), which determines which BIP-32 extended key version to use.

Add network property

---

src/index.ts

In #197 we forgot to export the `CryptographicFunctions` type.

Export `CryptographicFunctions` type

---

package.json
src/curves/ed25519.ts
yarn.lock

Tweak precompute window size for `ed25519`, reducing it from `8` to `4`, which results in a performance gain of about `-50%` on average when running under React Native.

perf: Tweak precompute window size for ed25519

---

src/BIP44CoinTypeNode.test.ts
src/BIP44CoinTypeNode.ts
src/BIP44Node.test.ts
src/BIP44Node.ts
src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/constants.ts
src/derivation.test.ts
src/derivers/bip39.test.ts
src/derivers/bip39.ts
src/utils.ts
test/fixtures.ts
test/reference-implementations.test.ts

This adds a new function to initialise a `key-tree` node from a BIP-39 seed. This can be used to skip the step from mnemonic phrase to seed, and can improve performance if the seed is already available.
This function is only supported for `secp256k1` and `ed25519` for now. `ed25519Bip32` may be added in the future.
Closes https://github.com/MetaMask/key-tree/issues/210

Add `fromSeed` function to `SLIP10Node`, `BIP44Node`, `BIP44CoinTypeNode`

---

src/SLIP10Node.test.ts
src/SLIP10Node.ts
src/constants.ts
src/curves/curve.ts
src/curves/ed25519Bip32.test.ts
src/curves/ed25519Bip32.ts
src/derivers/bip32.ts
src/derivers/bip39.ts
src/derivers/cip3.ts
src/derivers/shared.ts
src/guard.ts
src/index.test.ts
src/utils.ts

This optimises the performance of getting public keys in a couple of different ways:
- The `Curve.getPublicKey` function was changed to always return the public key synchronously. Every curve was already doing public key computations synchronously, so this lets us remove redundant `await`s and async functions.
- In cases where we need to compute the public key (to get the fingerprint for example), that public key is now re-used when possible, to avoid computing it twice.
- If a public key is not provided to `SLIP10Node`, it's now lazily computed, and cached. This avoids computing it unnecessarily when it's not used.
Closes #211.

Optimise performance of getting public keys

---

.github/workflows/build-lint-test.yml
.github/workflows/create-release-pr.yml
.github/workflows/main.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-release.yml
.github/workflows/security-code-scanner.yml

This updates all workflows to use `MetaMask/action-checkout-and-setup` instead of `actions/checkout`, `actions/setup-node` and `actions/cache`.

Update workflows to use `MetaMask/action-checkout-and-setup`

---

src/curves/secp256k1.ts

Tweak the precompute window for `secp256k1` for improved performance on mobile.

perf: Tweak precompute window size for secp256k1
